import hashlib
import json
import os
import subprocess
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COMMAND = ROOT / "lifecycle" / "plan-nginx-migration.sh"
LEGACY_OVERRIDE = """# Generated by misp-docker-lifecycle-manager. Keep upstream docker-compose.yml unmodified.
services:
  misp-core:
    healthcheck:
      test: curl -ksSf --max-time 2 https://localhost/users/heartbeat > /dev/null || exit 1
      interval: 10s
      timeout: 3s
      retries: 12
      start_period: 60s
"""
NGINX_OVERRIDE = """# Generated by misp-docker-lifecycle-manager. Keep upstream docker-compose.yml unmodified.
# The separated upstream layout defines health checks for both misp-core and
# misp-nginx; do not overwrite those service-specific contracts here.
services: {}
"""


def tree_digest(path: Path) -> str:
    digest = hashlib.sha256()
    for item in sorted(path.rglob("*")):
        digest.update(str(item.relative_to(path)).encode())
        if item.is_file() and not item.is_symlink():
            digest.update(item.read_bytes())
    return digest.hexdigest()


def make_install(
    root: Path,
    env_lines: list[str],
    *,
    override: str = LEGACY_OVERRIDE,
    exposure: str = "reverse-proxy",
    state_base_url: str = "https://misp.example.com",
    proxy_bind: str = "127.0.0.1",
) -> Path:
    install = root / "install"
    install.mkdir()
    (install / "docker-compose.yml").write_text("services:\n  misp-core:\n    image: example.invalid/misp:fixture\n")
    subprocess.run(["git", "init", "-q", "-b", "master", str(install)], check=True)
    subprocess.run(["git", "-C", str(install), "config", "user.name", "Test"], check=True)
    subprocess.run(["git", "-C", str(install), "config", "user.email", "test@example.com"], check=True)
    subprocess.run(["git", "-C", str(install), "add", "docker-compose.yml"], check=True)
    subprocess.run(["git", "-C", str(install), "commit", "-qm", "fixture"], check=True)
    (install / ".env").write_text("\n".join(env_lines) + "\n")
    (install / ".installer-state.json").write_text(json.dumps({
        "installer": "misp-docker-lifecycle-manager",
        "install_dir": str(install),
        "upstream_repo": "https://github.com/MISP/misp-docker.git",
        "upstream_ref": "legacy-fixture",
        "exposure": exposure,
        "base_url": state_base_url,
        "proxy_bind_address": proxy_bind,
    }))
    (install / "docker-compose.override.yml").write_text(override)
    return install



def make_fake_bin(root: Path, *, backup_exit: int = 0, docker_log_name: str = "docker.log") -> Path:
    fake_bin = root / "bin"
    fake_bin.mkdir()
    docker_log = root / docker_log_name
    docker = fake_bin / "docker"
    docker.write_text(
        """#!/bin/sh
printf '%s\n' "$*" >> "$DOCKER_LOG"
case "$*" in
  *" ps --status running --services") printf 'db\nredis\n';;
  *" exec -T db "*) printf '%s\n' '-- fixture dump';;
  *" config") printf 'compose config ok\n';;
esac
"""
    )
    docker.chmod(0o755)
    sudo = fake_bin / "sudo"
    sudo.write_text("#!/bin/sh\nexec \"$@\"\n")
    sudo.chmod(0o755)
    if backup_exit:
        backup_marker = root / "backup-called"
        backup = fake_bin / "backup.sh"
        backup.write_text(f"#!/bin/sh\ntouch {backup_marker}\nexit {backup_exit}\n")
        backup.chmod(0o755)
    return fake_bin


def add_standard_generated_values(install: Path) -> None:
    current = (install / ".env").read_text()
    additions = """ADMIN_EMAIL=admin@example.com
ADMIN_PASSWORD=generated-secret
ADMIN_KEY=1234567890abcdef1234567890abcdef12345678
MYSQL_PASSWORD=generated-mysql
MYSQL_ROOT_PASSWORD=generated-root
REDIS_PASSWORD=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
ENCRYPTION_KEY=generated-encryption
SALT=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
UUID=11111111-2222-3333-4444-555555555555
CORE_TAG=v2.5.45
MODULES_TAG=v3.0.9
GUARD_TAG=v1.2
CORE_RUNNING_TAG=v2.5.45
MODULES_RUNNING_TAG=v3.0.9
GUARD_RUNNING_TAG=v1.2
"""
    (install / ".env").write_text(current + additions)
    ssl = install / "ssl"
    ssl.mkdir(exist_ok=True)
    (ssl / "cert.pem").write_text("fixture-cert\n")
    (ssl / "key.pem").write_text("fixture-key\n")
    (install / "template.env").write_text(
        "CORE_TAG=v2.5.45\nMODULES_TAG=v3.0.9\nGUARD_TAG=v1.2\n"
        "NGINX_HTTP_PORT=80\nNGINX_HTTPS_PORT=443\n"
    )
    (install / "docker-compose.yml").write_text(
        "services:\n  misp-core:\n    image: example.invalid/misp:fixture\n"
        "  misp-nginx:\n    image: example.invalid/nginx:fixture\n"
    )
    for name in ("configs", "logs", "files", "gnupg", "custom", "guard"):
        (install / name).mkdir(exist_ok=True)
    (install / "configs" / "config.php").write_text("fixture\n")

def run_plan(install: Path, output_format: str = "json") -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [str(COMMAND), "--install-dir", str(install), "--format", output_format],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )


class NginxMigrationPlanTests(unittest.TestCase):

    def test_migration_dry_run_is_default_and_does_not_backup_or_mutate(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            install = make_install(root, [
                "BASE_URL=https://misp.example.com",
                "CORE_HTTP_PORT=127.0.0.1:8080",
                "CORE_HTTPS_PORT=127.0.0.1:8443",
            ])
            add_standard_generated_values(install)
            before = tree_digest(install)
            fake_bin = make_fake_bin(root)
            env = {**os.environ, "PATH": str(fake_bin) + os.pathsep + os.environ["PATH"], "DOCKER_LOG": str(root / "docker.log")}
            result = subprocess.run(
                [str(ROOT / "lifecycle" / "migrate-nginx.sh"), "--install-dir", str(install)],
                cwd=ROOT, env=env, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False,
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(before, tree_digest(install))
            self.assertIn("Dry-run only", result.stderr)
            self.assertFalse((root / "docker.log").exists())

    def test_migration_blocker_prevents_backup_and_mutation(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            install = make_install(root, [
                "BASE_URL=https://misp.example.com",
                "CORE_HTTP_PORT=127.0.0.1:8080",
                "CORE_HTTPS_PORT=127.0.0.1:8443",
                "DISABLE_SSL_REDIRECT=manual-decision-required",
            ])
            add_standard_generated_values(install)
            before = tree_digest(install)
            fake_bin = make_fake_bin(root)
            env = {**os.environ, "PATH": str(fake_bin) + os.pathsep + os.environ["PATH"], "DOCKER_LOG": str(root / "docker.log")}
            result = subprocess.run(
                [str(ROOT / "lifecycle" / "migrate-nginx.sh"), "--install-dir", str(install), "--apply"],
                cwd=ROOT, env=env, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False,
            )
            self.assertNotEqual(result.returncode, 0)
            self.assertEqual(before, tree_digest(install))
            self.assertIn("planner reported blockers", result.stderr)
            self.assertFalse((root / "docker.log").exists())

    def test_migration_backup_failure_stops_before_mutation(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            install = make_install(root, [
                "BASE_URL=https://misp.example.com",
                "CORE_HTTP_PORT=127.0.0.1:8080",
                "CORE_HTTPS_PORT=127.0.0.1:8443",
            ])
            add_standard_generated_values(install)
            before = tree_digest(install)
            fake_bin = make_fake_bin(root, backup_exit=42)
            env = {**os.environ, "PATH": str(fake_bin) + os.pathsep + os.environ["PATH"], "DOCKER_LOG": str(root / "docker.log")}
            backup_root = root / "bad-backups"
            backup_root.mkdir(mode=0o777)
            backup_root.chmod(0o777)
            result = subprocess.run(
                [
                    str(ROOT / "lifecycle" / "migrate-nginx.sh"), "--install-dir", str(install),
                    "--backup-root", str(backup_root), "--apply",
                ],
                cwd=ROOT, env=env, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False,
            )
            self.assertNotEqual(result.returncode, 0)
            self.assertEqual(before, tree_digest(install))
            self.assertIn("backup.sh failed; no migration files were changed", result.stderr)
            self.assertFalse(any(backup_root.iterdir()))

    def test_standard_legacy_conversion_succeeds_after_validated_backup_and_emits_rollback(self):
        with tempfile.TemporaryDirectory() as td:
            root = Path(td)
            install = make_install(root, [
                "BASE_URL=https://misp.example.com",
                "CORE_HTTP_PORT=127.0.0.1:8080",
                "CORE_HTTPS_PORT=127.0.0.1:8443",
                "CONTENT_SECURITY_POLICY=frame-ancestors 'self'",
                "HSTS_MAX_AGE=31536000",
                "X_FRAME_OPTIONS=SAMEORIGIN",
                "FASTCGI_STATUS_LISTEN=127.0.0.1:9003",
            ])
            add_standard_generated_values(install)
            before = tree_digest(install)
            fake_bin = make_fake_bin(root)
            backup_root = root / "backups"
            backup_root.mkdir(mode=0o700)
            env = {**os.environ, "PATH": str(fake_bin) + os.pathsep + os.environ["PATH"], "DOCKER_LOG": str(root / "docker.log")}
            result = subprocess.run(
                [
                    str(ROOT / "lifecycle" / "migrate-nginx.sh"), "--install-dir", str(install),
                    "--backup-root", str(backup_root), "--apply",
                ],
                cwd=ROOT, env=env, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False,
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertNotEqual(before, tree_digest(install))
            env_text = (install / ".env").read_text()
            self.assertIn("BASE_URL=https://misp.example.com", env_text)
            self.assertIn("NGINX_HTTP_PORT=127.0.0.1:8080", env_text)
            self.assertIn("NGINX_HTTPS_PORT=127.0.0.1:8443", env_text)
            self.assertIn("NGINX_CONTENT_SECURITY_POLICY=frame-ancestors 'self'", env_text)
            self.assertIn("NGINX_HSTS_MAX_AGE=31536000", env_text)
            self.assertIn("NGINX_X_FRAME_OPTIONS=SAMEORIGIN", env_text)
            self.assertIn("FASTCGI_LISTEN_STATUS=127.0.0.1:9003", env_text)
            self.assertIn("CORE_RUNNING_TAG=v2.5.45", env_text)
            self.assertIn("generated-secret", env_text)
            self.assertNotRegex(env_text, r"(?m)^CORE_HTTP_PORT=")
            self.assertNotRegex(env_text, r"(?m)^CORE_HTTPS_PORT=")
            self.assertEqual((install / "docker-compose.override.yml").read_text(), NGINX_OVERRIDE)
            state = json.loads((install / ".installer-state.json").read_text())
            self.assertEqual(state["base_url"], "https://misp.example.com")
            self.assertEqual(state["exposure"], "reverse-proxy")
            self.assertEqual(state["proxy_bind_address"], "127.0.0.1")
            backups = [path for path in backup_root.iterdir() if path.is_dir()]
            self.assertEqual(len(backups), 1)
            self.assertTrue((backups[0] / "SHA256SUMS").exists())
            self.assertIn("NGINX migration complete", result.stdout)
            self.assertIn("Rollback: sudo ./lifecycle/restore.sh --backup-dir", result.stdout)
            self.assertIn(str(backups[0]), result.stdout)
            docker_calls = (root / "docker.log").read_text().splitlines()
            backup_call = next(i for i, call in enumerate(docker_calls) if "exec -T db" in call)
            self.assertTrue(backup_call >= 0)

    def test_complete_legacy_plan_is_stable_public_safe_and_non_mutating(self):
        with tempfile.TemporaryDirectory() as td:
            sentinel = "never-print-this-sentinel"
            install = make_install(Path(td), [
                "BASE_URL=https://misp.example.com",
                "CORE_HTTP_PORT=127.0.0.1:8080",
                "CORE_HTTPS_PORT=127.0.0.1:8443",
                f"CUSTOM_SENTINEL={sentinel}",
                "CONTENT_SECURITY_POLICY=frame-ancestors 'self'",
                "HSTS_MAX_AGE=31536000",
                "X_FRAME_OPTIONS=SAMEORIGIN",
                "FASTCGI_STATUS_LISTEN=127.0.0.1:9003",
            ])
            before = tree_digest(install)
            first = run_plan(install)
            second = run_plan(install)
            self.assertEqual(first.returncode, 0, first.stderr)
            self.assertEqual(first.stdout, second.stdout)
            self.assertEqual(before, tree_digest(install))
            self.assertNotIn(sentinel, first.stdout + first.stderr)
            self.assertNotIn(str(install), first.stdout + first.stderr)

            plan = json.loads(first.stdout)
            self.assertEqual(plan["schema_version"], 1)
            self.assertFalse(plan["mutation_performed"])
            self.assertEqual(plan["classification"], "legacy_complete")
            self.assertEqual(plan["disposition"], "ready_for_future_migration")
            self.assertEqual(plan["compatibility"], "pending")
            self.assertEqual(plan["blockers"], [])
            self.assertEqual(plan["preservation"]["base_url"], "preserve_https_intent")
            self.assertEqual(plan["preservation"]["proxy_bind"], "preserve_explicit_ipv4_bind")
            self.assertEqual(plan["preservation"]["tls"], "preserve_https_listener_and_redirect_default")
            actions = {(item["source"], item["target"]): item["action"] for item in plan["variable_actions"]}
            self.assertEqual(actions[("CONTENT_SECURITY_POLICY", "NGINX_CONTENT_SECURITY_POLICY")], "rename_preserving_value")
            self.assertEqual(actions[("HSTS_MAX_AGE", "NGINX_HSTS_MAX_AGE")], "rename_preserving_value")
            self.assertEqual(actions[("X_FRAME_OPTIONS", "NGINX_X_FRAME_OPTIONS")], "rename_preserving_value")
            self.assertEqual(actions[("FASTCGI_STATUS_LISTEN", "FASTCGI_LISTEN_STATUS")], "rename_preserving_value")

    def test_complete_nginx_layout_is_already_current(self):
        with tempfile.TemporaryDirectory() as td:
            install = make_install(Path(td), [
                "BASE_URL=https://misp.example.com",
                "NGINX_HTTP_PORT=127.0.0.1:8080",
                "NGINX_HTTPS_PORT=127.0.0.1:8443",
            ], override=NGINX_OVERRIDE)
            result = run_plan(install)
            self.assertEqual(result.returncode, 0, result.stderr)
            plan = json.loads(result.stdout)
            self.assertEqual(plan["classification"], "nginx_complete")
            self.assertEqual(plan["disposition"], "already_current")
            self.assertEqual(plan["blockers"], [])

    def test_mixed_incomplete_and_unrecognized_layouts_are_distinct(self):
        cases = {
            "mixed": [
                "BASE_URL=https://misp.example.com",
                "CORE_HTTP_PORT=80", "CORE_HTTPS_PORT=443", "NGINX_HTTP_PORT=80",
            ],
            "incomplete": ["BASE_URL=https://misp.example.com", "CORE_HTTP_PORT=80"],
            "ambiguous": ["BASE_URL=https://misp.example.com", "ADMIN_PASSWORD=secret"],
        }
        for expected, lines in cases.items():
            with self.subTest(expected=expected), tempfile.TemporaryDirectory() as td:
                install = make_install(Path(td), lines)
                result = run_plan(install)
                self.assertEqual(result.returncode, 2, result.stderr)
                plan = json.loads(result.stdout)
                self.assertEqual(plan["classification"], expected)
                self.assertEqual(plan["disposition"], "manual_review_required")
                self.assertTrue(plan["blockers"])
                self.assertNotIn("secret", result.stdout + result.stderr)

    def test_duplicate_migration_sensitive_key_is_ambiguous(self):
        with tempfile.TemporaryDirectory() as td:
            install = make_install(Path(td), [
                "BASE_URL=https://misp.example.com",
                "CORE_HTTP_PORT=127.0.0.1:8080",
                "CORE_HTTP_PORT=127.0.0.1:8080",
                "CORE_HTTPS_PORT=127.0.0.1:8443",
            ])
            result = run_plan(install)
            self.assertEqual(result.returncode, 2)
            plan = json.loads(result.stdout)
            self.assertEqual(plan["classification"], "ambiguous")
            self.assertIn("duplicate_migration_sensitive_key", plan["blockers"])

    def test_removed_redirect_setting_requires_explicit_tls_decision(self):
        with tempfile.TemporaryDirectory() as td:
            install = make_install(Path(td), [
                "BASE_URL=https://misp.example.com",
                "CORE_HTTP_PORT=127.0.0.1:8080",
                "CORE_HTTPS_PORT=127.0.0.1:8443",
                "DISABLE_SSL_REDIRECT=operator-private-value",
            ])
            result = run_plan(install)
            self.assertEqual(result.returncode, 2)
            plan = json.loads(result.stdout)
            self.assertIn("removed_ssl_redirect_requires_decision", plan["blockers"])
            self.assertEqual(plan["preservation"]["tls"], "manual_redirect_decision_required")
            self.assertNotIn("operator-private-value", result.stdout + result.stderr)

    def test_conflicting_old_and_new_optional_names_fail_closed(self):
        with tempfile.TemporaryDirectory() as td:
            install = make_install(Path(td), [
                "BASE_URL=https://misp.example.com",
                "CORE_HTTP_PORT=127.0.0.1:8080",
                "CORE_HTTPS_PORT=127.0.0.1:8443",
                "HSTS_MAX_AGE=old-private-value",
                "NGINX_HSTS_MAX_AGE=new-private-value",
            ])
            result = run_plan(install)
            self.assertEqual(result.returncode, 2)
            plan = json.loads(result.stdout)
            action = next(item for item in plan["variable_actions"] if item["source"] == "HSTS_MAX_AGE")
            self.assertEqual(action["action"], "conflict_requires_review")
            self.assertIn("renamed_variable_conflict", plan["blockers"])
            self.assertNotIn("private-value", result.stdout + result.stderr)

    def test_custom_or_additional_compose_overrides_block_future_automation(self):
        variants = (
            ("services:\n  misp-core:\n    ports: [\"8443:443\"]\n", None),
            (LEGACY_OVERRIDE, ("compose.override.yaml", "services: {}\n")),
        )
        for override, extra in variants:
            with self.subTest(extra=extra), tempfile.TemporaryDirectory() as td:
                install = make_install(Path(td), [
                    "BASE_URL=https://misp.example.com",
                    "CORE_HTTP_PORT=127.0.0.1:8080",
                    "CORE_HTTPS_PORT=127.0.0.1:8443",
                ], override=override)
                if extra:
                    (install / extra[0]).write_text(extra[1])
                result = run_plan(install)
                self.assertEqual(result.returncode, 2)
                plan = json.loads(result.stdout)
                self.assertEqual(plan["compose_override"], "custom_or_multiple")
                self.assertIn("custom_compose_override", plan["blockers"])

    def test_nonstandard_bind_and_state_mismatch_are_reported_without_values(self):
        with tempfile.TemporaryDirectory() as td:
            install = make_install(
                Path(td),
                [
                    "BASE_URL=https://private.example.invalid",
                    "CORE_HTTP_PORT=203.0.113.77:9080",
                    "CORE_HTTPS_PORT=203.0.113.77:9443",
                ],
                state_base_url="https://different.example.invalid",
                proxy_bind="198.51.100.42",
            )
            result = run_plan(install)
            self.assertEqual(result.returncode, 2)
            plan = json.loads(result.stdout)
            self.assertIn("nonstandard_port_mapping", plan["blockers"])
            self.assertIn("state_base_url_mismatch", plan["blockers"])
            self.assertIn("state_proxy_bind_mismatch", plan["blockers"])
            for private_value in (
                "private.example.invalid", "different.example.invalid",
                "203.0.113.77", "198.51.100.42",
            ):
                self.assertNotIn(private_value, result.stdout + result.stderr)

    def test_help_states_dry_run_boundary_and_exit_contract(self):
        result = subprocess.run(
            [str(COMMAND), "--help"], cwd=ROOT, text=True,
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False,
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("never changes deployment files", result.stdout)
        self.assertIn("Exit 2", result.stdout)
        self.assertIn("compatibility remains pending", result.stdout)


if __name__ == "__main__":
    unittest.main()
