import hashlib
import json
import subprocess
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COMMAND = ROOT / "lifecycle" / "plan-nginx-migration.sh"
LEGACY_OVERRIDE = """# Generated by misp-docker-lifecycle-manager. Keep upstream docker-compose.yml unmodified.
services:
  misp-core:
    healthcheck:
      test: curl -ksSf --max-time 2 https://localhost/users/heartbeat > /dev/null || exit 1
      interval: 10s
      timeout: 3s
      retries: 12
      start_period: 60s
"""
NGINX_OVERRIDE = """# Generated by misp-docker-lifecycle-manager. Keep upstream docker-compose.yml unmodified.
# The separated upstream layout defines health checks for both misp-core and
# misp-nginx; do not overwrite those service-specific contracts here.
services: {}
"""


def tree_digest(path: Path) -> str:
    digest = hashlib.sha256()
    for item in sorted(path.rglob("*")):
        digest.update(str(item.relative_to(path)).encode())
        if item.is_file() and not item.is_symlink():
            digest.update(item.read_bytes())
    return digest.hexdigest()


def make_install(
    root: Path,
    env_lines: list[str],
    *,
    override: str = LEGACY_OVERRIDE,
    exposure: str = "reverse-proxy",
    state_base_url: str = "https://misp.example.com",
    proxy_bind: str = "127.0.0.1",
) -> Path:
    install = root / "install"
    install.mkdir()
    (install / "docker-compose.yml").write_text("services:\n  misp-core:\n    image: example.invalid/misp:fixture\n")
    subprocess.run(["git", "init", "-q", "-b", "master", str(install)], check=True)
    subprocess.run(["git", "-C", str(install), "config", "user.name", "Test"], check=True)
    subprocess.run(["git", "-C", str(install), "config", "user.email", "test@example.com"], check=True)
    subprocess.run(["git", "-C", str(install), "add", "docker-compose.yml"], check=True)
    subprocess.run(["git", "-C", str(install), "commit", "-qm", "fixture"], check=True)
    (install / ".env").write_text("\n".join(env_lines) + "\n")
    (install / ".installer-state.json").write_text(json.dumps({
        "installer": "misp-docker-lifecycle-manager",
        "install_dir": str(install),
        "upstream_repo": "https://github.com/MISP/misp-docker.git",
        "upstream_ref": "legacy-fixture",
        "exposure": exposure,
        "base_url": state_base_url,
        "proxy_bind_address": proxy_bind,
    }))
    (install / "docker-compose.override.yml").write_text(override)
    return install


def run_plan(install: Path, output_format: str = "json") -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [str(COMMAND), "--install-dir", str(install), "--format", output_format],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )


class NginxMigrationPlanTests(unittest.TestCase):
    def test_complete_legacy_plan_is_stable_public_safe_and_non_mutating(self):
        with tempfile.TemporaryDirectory() as td:
            sentinel = "never-print-this-sentinel"
            install = make_install(Path(td), [
                "BASE_URL=https://misp.example.com",
                "CORE_HTTP_PORT=127.0.0.1:8080",
                "CORE_HTTPS_PORT=127.0.0.1:8443",
                f"CUSTOM_SENTINEL={sentinel}",
                "CONTENT_SECURITY_POLICY=frame-ancestors 'self'",
                "HSTS_MAX_AGE=31536000",
                "X_FRAME_OPTIONS=SAMEORIGIN",
                "FASTCGI_STATUS_LISTEN=127.0.0.1:9003",
            ])
            before = tree_digest(install)
            first = run_plan(install)
            second = run_plan(install)
            self.assertEqual(first.returncode, 0, first.stderr)
            self.assertEqual(first.stdout, second.stdout)
            self.assertEqual(before, tree_digest(install))
            self.assertNotIn(sentinel, first.stdout + first.stderr)
            self.assertNotIn(str(install), first.stdout + first.stderr)

            plan = json.loads(first.stdout)
            self.assertEqual(plan["schema_version"], 1)
            self.assertFalse(plan["mutation_performed"])
            self.assertEqual(plan["classification"], "legacy_complete")
            self.assertEqual(plan["disposition"], "ready_for_future_migration")
            self.assertEqual(plan["compatibility"], "pending")
            self.assertEqual(plan["blockers"], [])
            self.assertEqual(plan["preservation"]["base_url"], "preserve_https_intent")
            self.assertEqual(plan["preservation"]["proxy_bind"], "preserve_explicit_ipv4_bind")
            self.assertEqual(plan["preservation"]["tls"], "preserve_https_listener_and_redirect_default")
            actions = {(item["source"], item["target"]): item["action"] for item in plan["variable_actions"]}
            self.assertEqual(actions[("CONTENT_SECURITY_POLICY", "NGINX_CONTENT_SECURITY_POLICY")], "rename_preserving_value")
            self.assertEqual(actions[("HSTS_MAX_AGE", "NGINX_HSTS_MAX_AGE")], "rename_preserving_value")
            self.assertEqual(actions[("X_FRAME_OPTIONS", "NGINX_X_FRAME_OPTIONS")], "rename_preserving_value")
            self.assertEqual(actions[("FASTCGI_STATUS_LISTEN", "FASTCGI_LISTEN_STATUS")], "rename_preserving_value")

    def test_complete_nginx_layout_is_already_current(self):
        with tempfile.TemporaryDirectory() as td:
            install = make_install(Path(td), [
                "BASE_URL=https://misp.example.com",
                "NGINX_HTTP_PORT=127.0.0.1:8080",
                "NGINX_HTTPS_PORT=127.0.0.1:8443",
            ], override=NGINX_OVERRIDE)
            result = run_plan(install)
            self.assertEqual(result.returncode, 0, result.stderr)
            plan = json.loads(result.stdout)
            self.assertEqual(plan["classification"], "nginx_complete")
            self.assertEqual(plan["disposition"], "already_current")
            self.assertEqual(plan["blockers"], [])

    def test_mixed_incomplete_and_unrecognized_layouts_are_distinct(self):
        cases = {
            "mixed": [
                "BASE_URL=https://misp.example.com",
                "CORE_HTTP_PORT=80", "CORE_HTTPS_PORT=443", "NGINX_HTTP_PORT=80",
            ],
            "incomplete": ["BASE_URL=https://misp.example.com", "CORE_HTTP_PORT=80"],
            "ambiguous": ["BASE_URL=https://misp.example.com", "ADMIN_PASSWORD=secret"],
        }
        for expected, lines in cases.items():
            with self.subTest(expected=expected), tempfile.TemporaryDirectory() as td:
                install = make_install(Path(td), lines)
                result = run_plan(install)
                self.assertEqual(result.returncode, 2, result.stderr)
                plan = json.loads(result.stdout)
                self.assertEqual(plan["classification"], expected)
                self.assertEqual(plan["disposition"], "manual_review_required")
                self.assertTrue(plan["blockers"])
                self.assertNotIn("secret", result.stdout + result.stderr)

    def test_duplicate_migration_sensitive_key_is_ambiguous(self):
        with tempfile.TemporaryDirectory() as td:
            install = make_install(Path(td), [
                "BASE_URL=https://misp.example.com",
                "CORE_HTTP_PORT=127.0.0.1:8080",
                "CORE_HTTP_PORT=127.0.0.1:8080",
                "CORE_HTTPS_PORT=127.0.0.1:8443",
            ])
            result = run_plan(install)
            self.assertEqual(result.returncode, 2)
            plan = json.loads(result.stdout)
            self.assertEqual(plan["classification"], "ambiguous")
            self.assertIn("duplicate_migration_sensitive_key", plan["blockers"])

    def test_removed_redirect_setting_requires_explicit_tls_decision(self):
        with tempfile.TemporaryDirectory() as td:
            install = make_install(Path(td), [
                "BASE_URL=https://misp.example.com",
                "CORE_HTTP_PORT=127.0.0.1:8080",
                "CORE_HTTPS_PORT=127.0.0.1:8443",
                "DISABLE_SSL_REDIRECT=operator-private-value",
            ])
            result = run_plan(install)
            self.assertEqual(result.returncode, 2)
            plan = json.loads(result.stdout)
            self.assertIn("removed_ssl_redirect_requires_decision", plan["blockers"])
            self.assertEqual(plan["preservation"]["tls"], "manual_redirect_decision_required")
            self.assertNotIn("operator-private-value", result.stdout + result.stderr)

    def test_conflicting_old_and_new_optional_names_fail_closed(self):
        with tempfile.TemporaryDirectory() as td:
            install = make_install(Path(td), [
                "BASE_URL=https://misp.example.com",
                "CORE_HTTP_PORT=127.0.0.1:8080",
                "CORE_HTTPS_PORT=127.0.0.1:8443",
                "HSTS_MAX_AGE=old-private-value",
                "NGINX_HSTS_MAX_AGE=new-private-value",
            ])
            result = run_plan(install)
            self.assertEqual(result.returncode, 2)
            plan = json.loads(result.stdout)
            action = next(item for item in plan["variable_actions"] if item["source"] == "HSTS_MAX_AGE")
            self.assertEqual(action["action"], "conflict_requires_review")
            self.assertIn("renamed_variable_conflict", plan["blockers"])
            self.assertNotIn("private-value", result.stdout + result.stderr)

    def test_custom_or_additional_compose_overrides_block_future_automation(self):
        variants = (
            ("services:\n  misp-core:\n    ports: [\"8443:443\"]\n", None),
            (LEGACY_OVERRIDE, ("compose.override.yaml", "services: {}\n")),
        )
        for override, extra in variants:
            with self.subTest(extra=extra), tempfile.TemporaryDirectory() as td:
                install = make_install(Path(td), [
                    "BASE_URL=https://misp.example.com",
                    "CORE_HTTP_PORT=127.0.0.1:8080",
                    "CORE_HTTPS_PORT=127.0.0.1:8443",
                ], override=override)
                if extra:
                    (install / extra[0]).write_text(extra[1])
                result = run_plan(install)
                self.assertEqual(result.returncode, 2)
                plan = json.loads(result.stdout)
                self.assertEqual(plan["compose_override"], "custom_or_multiple")
                self.assertIn("custom_compose_override", plan["blockers"])

    def test_nonstandard_bind_and_state_mismatch_are_reported_without_values(self):
        with tempfile.TemporaryDirectory() as td:
            install = make_install(
                Path(td),
                [
                    "BASE_URL=https://private.example.invalid",
                    "CORE_HTTP_PORT=203.0.113.77:9080",
                    "CORE_HTTPS_PORT=203.0.113.77:9443",
                ],
                state_base_url="https://different.example.invalid",
                proxy_bind="198.51.100.42",
            )
            result = run_plan(install)
            self.assertEqual(result.returncode, 2)
            plan = json.loads(result.stdout)
            self.assertIn("nonstandard_port_mapping", plan["blockers"])
            self.assertIn("state_base_url_mismatch", plan["blockers"])
            self.assertIn("state_proxy_bind_mismatch", plan["blockers"])
            for private_value in (
                "private.example.invalid", "different.example.invalid",
                "203.0.113.77", "198.51.100.42",
            ):
                self.assertNotIn(private_value, result.stdout + result.stderr)

    def test_help_states_dry_run_boundary_and_exit_contract(self):
        result = subprocess.run(
            [str(COMMAND), "--help"], cwd=ROOT, text=True,
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False,
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertIn("never changes deployment files", result.stdout)
        self.assertIn("Exit 2", result.stdout)
        self.assertIn("compatibility remains pending", result.stdout)


if __name__ == "__main__":
    unittest.main()
