#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib.sh"

usage() {
  cat <<'EOF'
Plan a future CORE_* to separated NGINX_* front-end migration without changing files.

Usage:
  ./lifecycle/plan-nginx-migration.sh [options]

Options:
  --install-dir PATH      Deployment directory to inspect (default: /opt/misp-docker)
  --format FORMAT         Output format: text or json (default: text)
  -h, --help              Show this help
  --version               Show manager version

This command is read-only: it never changes deployment files. It emits a
public-safe plan that omits raw .env values, install paths, hostnames, IPs,
secrets, logs, and topology details.

Exit codes:
  0                        Layout is complete and has no migration blockers
  Exit 2                   Manual review is required before future automation
  1                        Local invocation or inspection error

compatibility remains pending until an exact manager release/ref and official
MISP Docker component tuple pass validation; this helper does not make a
validated-compatibility claim.
EOF
}

INSTALL_DIR="/opt/misp-docker"
FORMAT="text"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --install-dir) INSTALL_DIR="${2:-}"; shift 2;;
    --format) FORMAT="${2:-}"; shift 2;;
    -h|--help) usage; exit 0;;
    --version) print_version; exit 0;;
    *) fatal "Unknown argument: $1";;
  esac
done

[[ "$FORMAT" =~ ^(text|json)$ ]] || fatal "format must be text or json"

python3 - "$INSTALL_DIR" "$FORMAT" <<'PY'
from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

install_dir = Path(sys.argv[1])
output_format = sys.argv[2]

LEGACY_OVERRIDE = """# Generated by misp-docker-lifecycle-manager. Keep upstream docker-compose.yml unmodified.
services:
  misp-core:
    healthcheck:
      test: curl -ksSf --max-time 2 https://localhost/users/heartbeat > /dev/null || exit 1
      interval: 10s
      timeout: 3s
      retries: 12
      start_period: 60s
"""
NGINX_OVERRIDE = """# Generated by misp-docker-lifecycle-manager. Keep upstream docker-compose.yml unmodified.
# The separated upstream layout defines health checks for both misp-core and
# misp-nginx; do not overwrite those service-specific contracts here.
services: {}
"""
PORT_KEYS = ("CORE_HTTP_PORT", "CORE_HTTPS_PORT", "NGINX_HTTP_PORT", "NGINX_HTTPS_PORT")
LEGACY_REQUIRED = ("CORE_HTTP_PORT", "CORE_HTTPS_PORT")
NGINX_REQUIRED = ("NGINX_HTTP_PORT", "NGINX_HTTPS_PORT")
MIGRATION_KEYS = {
    "CONTENT_SECURITY_POLICY": "NGINX_CONTENT_SECURITY_POLICY",
    "HSTS_MAX_AGE": "NGINX_HSTS_MAX_AGE",
    "X_FRAME_OPTIONS": "NGINX_X_FRAME_OPTIONS",
    "FASTCGI_STATUS_LISTEN": "FASTCGI_LISTEN_STATUS",
}
SENSITIVE_KEYS = set(PORT_KEYS) | set(MIGRATION_KEYS) | set(MIGRATION_KEYS.values()) | {"BASE_URL", "DISABLE_SSL_REDIRECT"}


def add_blocker(blockers: list[str], blocker: str) -> None:
    if blocker not in blockers:
        blockers.append(blocker)


def parse_env(path: Path) -> tuple[dict[str, str], set[str]]:
    values: dict[str, str] = {}
    duplicates: set[str] = set()
    pattern = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=")
    for line in path.read_text(errors="strict").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        match = pattern.match(line)
        if not match:
            continue
        key = match.group(1)
        value = line.split("=", 1)[1].strip().strip('"').strip("'")
        if key in values:
            duplicates.add(key)
        values[key] = value
    return values, duplicates


def classify(values: dict[str, str], blockers: list[str]) -> str:
    legacy_present = [key for key in LEGACY_REQUIRED if values.get(key, "")]
    nginx_present = [key for key in NGINX_REQUIRED if values.get(key, "")]
    legacy_any = bool(legacy_present)
    nginx_any = bool(nginx_present)
    legacy_complete = len(legacy_present) == 2
    nginx_complete = len(nginx_present) == 2
    if legacy_any and nginx_any:
        add_blocker(blockers, "mixed_frontend_port_families")
        return "mixed"
    if legacy_any:
        if legacy_complete:
            return "legacy_complete"
        add_blocker(blockers, "incomplete_frontend_port_family")
        return "incomplete"
    if nginx_any:
        if nginx_complete:
            return "nginx_complete"
        add_blocker(blockers, "incomplete_frontend_port_family")
        return "incomplete"
    add_blocker(blockers, "unrecognized_frontend_port_family")
    return "ambiguous"


def port_mapping_status(values: dict[str, str], classification: str) -> str:
    if classification.startswith("legacy"):
        http = values.get("CORE_HTTP_PORT", "")
        https = values.get("CORE_HTTPS_PORT", "")
    elif classification.startswith("nginx"):
        http = values.get("NGINX_HTTP_PORT", "")
        https = values.get("NGINX_HTTPS_PORT", "")
    else:
        return "not_evaluated"
    if http == "127.0.0.1:8080" and https == "127.0.0.1:8443":
        return "standard_reverse_proxy_loopback"
    if http == "80" and https == "443":
        return "standard_direct_qa"
    return "nonstandard"


def compose_override_status(path: Path) -> str:
    override_names = [
        "docker-compose.override.yml",
        "docker-compose.override.yaml",
        "compose.override.yml",
        "compose.override.yaml",
    ]
    existing = [name for name in override_names if (path / name).exists()]
    if not existing:
        return "missing"
    if existing == ["docker-compose.override.yml"]:
        content = (path / "docker-compose.override.yml").read_text(errors="strict")
        if content == LEGACY_OVERRIDE:
            return "managed_legacy"
        if content == NGINX_OVERRIDE:
            return "managed_nginx"
    return "custom_or_multiple"


def preservation(values: dict[str, str], state: dict[str, Any], blockers: list[str], mapping_status: str) -> dict[str, str]:
    base_url = "not_evaluated"
    env_base_url = values.get("BASE_URL", "")
    state_base_url = state.get("base_url") if isinstance(state, dict) else None
    if env_base_url:
        if isinstance(state_base_url, str) and state_base_url and state_base_url != env_base_url:
            base_url = "manual_base_url_review_required"
            add_blocker(blockers, "state_base_url_mismatch")
        else:
            base_url = "preserve_https_intent" if env_base_url.startswith("https://") else "preserve_http_intent"

    proxy_bind = "not_evaluated"
    if mapping_status == "standard_reverse_proxy_loopback":
        proxy_bind = "preserve_explicit_ipv4_bind"
        state_bind = state.get("proxy_bind_address") if isinstance(state, dict) else None
        if isinstance(state_bind, str) and state_bind and state_bind != "127.0.0.1":
            proxy_bind = "manual_proxy_bind_review_required"
            add_blocker(blockers, "state_proxy_bind_mismatch")
    elif mapping_status == "standard_direct_qa":
        proxy_bind = "preserve_direct_exposure"
    elif mapping_status == "nonstandard":
        proxy_bind = "manual_proxy_bind_review_required"
        add_blocker(blockers, "nonstandard_port_mapping")
        state_bind = state.get("proxy_bind_address") if isinstance(state, dict) else None
        if isinstance(state_bind, str) and state_bind:
            add_blocker(blockers, "state_proxy_bind_mismatch")

    tls = "preserve_https_listener_and_redirect_default"
    if values.get("DISABLE_SSL_REDIRECT", ""):
        tls = "manual_redirect_decision_required"
        add_blocker(blockers, "removed_ssl_redirect_requires_decision")
    return {"base_url": base_url, "proxy_bind": proxy_bind, "tls": tls}


def variable_actions(values: dict[str, str], blockers: list[str]) -> list[dict[str, str]]:
    actions: list[dict[str, str]] = []
    for source, target in MIGRATION_KEYS.items():
        source_present = bool(values.get(source, ""))
        target_present = bool(values.get(target, ""))
        if source_present and target_present:
            action = "conflict_requires_review"
            add_blocker(blockers, "renamed_variable_conflict")
        elif source_present:
            action = "rename_preserving_value"
        elif target_present:
            action = "already_renamed"
        else:
            action = "not_set"
        actions.append({"source": source, "target": target, "action": action})
    return actions


def stable_blockers(blockers: list[str]) -> list[str]:
    order = [
        "duplicate_migration_sensitive_key",
        "mixed_frontend_port_families",
        "incomplete_frontend_port_family",
        "unrecognized_frontend_port_family",
        "renamed_variable_conflict",
        "removed_ssl_redirect_requires_decision",
        "custom_compose_override",
        "nonstandard_port_mapping",
        "state_base_url_mismatch",
        "state_proxy_bind_mismatch",
        "missing_install_file",
    ]
    return sorted(blockers, key=lambda item: (order.index(item) if item in order else len(order), item))


blockers: list[str] = []
errors: list[str] = []
env_file = install_dir / ".env"
state_file = install_dir / ".installer-state.json"
values: dict[str, str] = {}
duplicates: set[str] = set()
state: dict[str, Any] = {}
duplicate_sensitive = False

try:
    if not install_dir.is_dir():
        add_blocker(blockers, "missing_install_file")
        errors.append("install_dir_missing")
    if env_file.is_file():
        values, duplicates = parse_env(env_file)
    else:
        add_blocker(blockers, "missing_install_file")
        errors.append("env_missing")
    if state_file.is_file():
        loaded = json.loads(state_file.read_text(errors="strict"))
        if isinstance(loaded, dict):
            state = loaded
    duplicate_sensitive = bool(duplicates & SENSITIVE_KEYS)
    if duplicate_sensitive:
        add_blocker(blockers, "duplicate_migration_sensitive_key")
except Exception:
    print("Unable to inspect deployment metadata safely", file=sys.stderr)
    sys.exit(1)

classification = classify(values, blockers)
if 'duplicate_sensitive' in globals() and duplicate_sensitive:
    classification = "ambiguous"
compose_status = compose_override_status(install_dir) if install_dir.is_dir() else "missing"
if compose_status == "custom_or_multiple":
    add_blocker(blockers, "custom_compose_override")

mapping_status = port_mapping_status(values, classification)
preserve = preservation(values, state, blockers, mapping_status)
actions = variable_actions(values, blockers)
blockers = stable_blockers(blockers)

if classification == "nginx_complete" and not blockers:
    disposition = "already_current"
elif classification == "legacy_complete" and not blockers:
    disposition = "ready_for_future_migration"
else:
    disposition = "manual_review_required"

plan: dict[str, Any] = {
    "schema_version": 1,
    "mutation_performed": False,
    "compatibility": "pending",
    "classification": classification,
    "disposition": disposition,
    "blockers": blockers,
    "compose_override": compose_status,
    "port_mapping": mapping_status,
    "preservation": preserve,
    "variable_actions": actions,
    "notes": [
        "read_only_plan_only",
        "public_safe_values_omitted",
        "compatibility_pending_exact_validation",
    ],
}

if output_format == "json":
    print(json.dumps(plan, sort_keys=True, separators=(",", ":")))
else:
    print(f"NGINX migration plan: {classification}")
    print(f"Disposition: {disposition}")
    print("Mutation performed: false")
    print("Compatibility: pending")
    if blockers:
        print("Blockers:")
        for blocker in blockers:
            print(f"- {blocker}")
    else:
        print("Blockers: none")

sys.exit(0 if not blockers and classification in {"legacy_complete", "nginx_complete"} else 2)
PY
